config/routes.rb
Pumpgrade::Application.routes.draw do
  resources :midterms

  get "course/course_notes"
  get "course/assignments"
  get "course/midterms"
  get "course/finals"
  get "course/video_tutorials"
  get "course/forums"
  get "course/index"
  get "course/similar_courses"

end

app/models/midterm.rb
class Midterm < ActiveRecord::Base
  validates :school, :courseCode, :year, :professor, :semester, presence: true
  validates :year, :numericality => { :greater_than_or_equal_to => 1990, :less_than_or_equal_to => 2014 }
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/course_controller.rb
class CourseController < ApplicationController
  def index
  end
  
  def course_Notes
  end

  def assignments
  end

  def midterms
  end

  def finals
  end

  def video_tutorials
  end

  def forums
  end
  
  def similar_courses
  end
end

app/controllers/midterms_controller.rb
class MidtermsController < ApplicationController
  before_action :set_midterm, only: [:show, :edit, :update, :destroy]

  # GET /midterms
  # GET /midterms.json
  def index
    @midterms = Midterm.all
  end

  # GET /midterms/1
  # GET /midterms/1.json
  def show
  end

  # GET /midterms/new
  def new
    @midterm = Midterm.new
  end

  # GET /midterms/1/edit
  def edit
  end

  # POST /midterms
  # POST /midterms.json
  def create
    @midterm = Midterm.new(midterm_params)

    respond_to do |format|
      if @midterm.save
        format.html { redirect_to @midterm, notice: 'Midterm was successfully created.' }
        format.json { render action: 'show', status: :created, location: @midterm }
        #Send an email with uploaded file and parameters
        MidtermSubmit.new_submission_email(@midterm).deliver
      else
        format.html { render action: 'new' }
        format.json { render json: @midterm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /midterms/1
  # PATCH/PUT /midterms/1.json
  def update
    respond_to do |format|
      if @midterm.update(midterm_params)
        format.html { redirect_to @midterm, notice: 'Midterm was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @midterm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /midterms/1
  # DELETE /midterms/1.json
  def destroy
    @midterm.destroy
    respond_to do |format|
      format.html { redirect_to midterms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_midterm
      @midterm = Midterm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def midterm_params
      params.require(:midterm).permit(:school, :courseCode, :year, :corrected, :professor, :semester)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/midterms_helper.rb
module MidtermsHelper
end

app/views/course/assignments.html.erb
<h1>Course#Assignments</h1>
<p>
	<a href="/course/index">Home</a>
	<a href="/course/course_notes">Course notes</a>
	<a href="/course/finals">Finals</a>
	<a href="/course/forums">Forums</a>
	<a href="/course/midterms">Midterms</a>
	<a href="/course/video_tutorials">Video tutorials</a>	
	<a href="/course/similar_courses">Similar courses</a>				
</p>

app/views/course/course_notes.html.erb
<h1>Course#Course_Notes</h1>
<p>
	<a href="/course/index">Home</a>
	<a href="/course/assignments">Assignments</a>
	<a href="/course/finals">Finals</a>
	<a href="/course/forums">Forums</a>
	<a href="/course/midterms">Midterms</a>
	<a href="/course/video_tutorials">Video tutorials</a>	
	<a href="/course/similar_courses">Similar courses</a>	
</p>

app/views/course/finals.html.erb
<h1>Course#Finals</h1>
<p>
	<a href="/course/index">Home</a>
	<a href="/course/assignments">Assignments</a>
	<a href="/course/course_notes">Course notes</a>
	<a href="/course/forums">Forums</a>
	<a href="/course/midterms">Midterms</a>
	<a href="/course/video_tutorials">Video tutorials</a>	
	<a href="/course/similar_courses">Similar courses</a>	
</p>

app/views/course/forums.html.erb
<h1>Course#Forums</h1>
<p>
	<a href="/course/index">Home</a>
	<a href="/course/assignments">Assignments</a>
	<a href="/course/course_notes">Course notes</a>
	<a href="/course/finals">Finals</a>
	<a href="/course/midterms">Midterms</a>
	<a href="/course/video_tutorials">Video tutorials</a>	
	<a href="/course/similar_courses">Similar courses</a>	
</p>

app/views/course/index.html.erb
<h1>Course#Index</h1>
<p>
	<a href="/course/assignments">Assignments</a>
	<a href="/course/course_notes">Course notes</a>
	<a href="/course/finals">Finals</a>
	<a href="/course/forums">Forums</a>
	<%= link_to 'Midterms', midterms_path %>
	<a href="/course/video_tutorials">Video tutorials</a>				
</p>

app/views/course/midterms.html.erb
<h1>Course#Midterms</h1>
<nav>
	<a href="/course/index">Home</a>
	<a href="/course/assignments">Assignments</a>
	<a href="/course/course_notes">Course notes</a>
	<a href="/course/finals">Finals</a>
	<a href="/course/forums">Forums</a>
	<a href="/course/video_tutorials">Video tutorials</a>	
	<a href="/course/similar_courses">Similar courses</a>	
</nav>

app/views/course/similar_courses.html.erb
<h1>Course#Midterms</h1>
<p>
	<a href="/course/index">Home</a>
	<a href="/course/assignments">Assignments</a>
	<a href="/course/course_notes">Course notes</a>
	<a href="/course/finals">Finals</a>
	<a href="/course/forums">Forums</a>
	<a href="/course/midterms">Midterms</a>
	<a href="/course/video_tutorials">Video tutorials</a>	
</p>

app/views/course/video_tutorials.html.erb
<h1>Course#Video_Tutorials</h1>
<p>
	<a href="/course/index">Home</a>
	<a href="/course/assignments">Assignments</a>
	<a href="/course/course_notes">Course notes</a>
	<a href="/course/finals">Finals</a>
	<a href="/course/forums">Forums</a>
	<a href="/course/midterms">Midterms</a>
	<a href="/course/video_tutorials">Video tutorials</a>	
	<a href="/course/similar_courses">Similar courses</a>	
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pumpgrade</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/midterms/_form.html.erb
<%= form_for @midterm, :multipart => true do |f| %>
  <% if @midterm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@midterm.errors.count, "error") %> prohibited this midterm from being saved:</h2>

      <ul>
      <% @midterm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div class="text-center">
	  <div class="field">
	    <%= f.label :school %><br>
	    <%= f.text_field :school %>
	  </div>
	  <div class="field">
	    <%= f.label :courseCode, "Course Code"%><br>
	    <%= f.text_field :courseCode %>
	  </div>
	  <div class="field">
	    <%= f.label :year %><br>
	    <%= f.number_field :year %>
	  </div>
	  <div class="field">
	    <%= f.label :corrected, "Does this file contain answers?" %><br>
	    <%= f.check_box :corrected %>
	  </div>
	  <div class="field">
	    <%= f.label :professor %><br>
	    <%= f.text_field :professor %>
	  </div>
	  <div class="field">
	    <%= f.label :semester, 'Semester (Fall, Winter, Summer)'%><br>
	    <%= f.text_field :semester %>
	  </div>
	 <!-- <div class="field">>
	  	<%= f.label :file, "Select file to submit" %><br>
	  	<%= f.file_field :file %>
	 </div>-->
	  <div class="actions">
	    <%= f.submit "Submit" %>
	  </div>
	</div>
<% end %>

app/views/midterms/_header.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header navbar-static-top">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">CheetahGrades</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">Course Notes<a href="#"></a></li>
        <li><a href="#">Assignments</a></li>
        <li class="active"><a href="#">Midterms</a></li>
        <li><a href="#">Finals</a></li>
        <li><a href="#">Forums</a></li>
        <li><a href="#">Similar Courses</a></li>
        <li><a href="#">Videos</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Site Navigation<b class="caret"></b></a>
         <!-- <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
         </ul>-->
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/midterms/edit.html.erb
<%= render 'header' %>

<h1>Editing midterm</h1>

<%= render 'form' %>

<%= link_to 'Show', @midterm %> |
<%= link_to 'Back', midterms_path %>

app/views/midterms/index.html.erb
<%= render 'header' %>
<h1 class="text-center">Available Midterms</h1>

<table class="table">
  <thead>
    <tr>
      <th>Year</th>
      <th>School</th>
      <th>Coursecode</th>
      <th>Corrected</th>
      <th>Professor</th>
      <th>Semester</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @midterms.each do |midterm| %>
      <tr>
      	<td><%= midterm.year %></td>
        <td><%= midterm.school %></td>
        <td><%= midterm.courseCode %></td>
        <td><%= midterm.corrected %></td>
        <td><%= midterm.professor %></td>
        <td><%= midterm.semester %></td>
        <td><%= link_to 'Show', midterm %></td>
        <td><%= link_to 'Edit', edit_midterm_path(midterm) %></td>
        <td><%= link_to 'Destroy', midterm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Submit a Midterm!', new_midterm_path %>

app/views/midterms/new.html.erb
<%= render 'header' %>
<h1 class="text-center">Submit a file</h1>

<%= render 'form' %>

<p class="text-center"><%= link_to 'Back', midterms_path %></p>

app/views/midterms/show.html.erb
<%= render 'header' %>

<p id="notice"><%= notice %></p>

<p>
  <strong>School:</strong>
  <%= @midterm.school %>
</p>

<p>
  <strong>Coursecode:</strong>
  <%= @midterm.courseCode %>
</p>

<p>
  <strong>Year:</strong>
  <%= @midterm.year %>
</p>

<p>
  <strong>Corrected:</strong>
  <%= @midterm.corrected %>
</p>

<p>
  <strong>Professor:</strong>
  <%= @midterm.professor %>
</p>

<p>
  <strong>Semester:</strong>
  <%= @midterm.semester %>
</p>

<%= link_to 'Edit', edit_midterm_path(@midterm) %> |
<%= link_to 'Back', midterms_path %>